apiVersion: v1
kind: Service
metadata:
  name: time-series-service
spec:
  type: LoadBalancer  # Expose to the internet
  selector:
    app: time-series-app
  ports:
  - protocol: TCP
    port: 80         # Public-facing port
    targetPort: 5000 # Flask app's internal port

